config/routes.rb
Emails1::Application.routes.draw do
  get "log_out" => "login#destroy", :as => "log_out"
  get "home" => "users#index", :as => "home"
  get  "sign_up" => "users#new", :as => "sign_up"
  get "login" => "login#new", :as => "login"
  get "welcome" => "login#show", :as => "welcome"
  get "account" => "login#edit", :as => "account"

  resources :users
  resources :login

  root :to => 'users#index'

end

app/models/user.rb
require 'openssl'
require 'base64'

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation,:firstname, :lastname,:mobileno,:address,:sex,:passportno,:pancardno
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password,:on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      nil
    end
  end
 def encrypt_password
     if password.present?
       self.password_salt = BCrypt::Engine.generate_salt
       self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
     end
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :set_no_cache



  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 2020 00:00:00 GMT"
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
    @user = User.new
  end
  def create
    user = User.authenticate(params[:email],params[:password])
    if user
      session[:user_id] = user.id
      redirect_to  :action =>'show', :status => 303
    else
      flash.now.alert = "Invalid email or password"
      render 'new'
    end
  end
  def show
    @user = User.all
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Log Out"
  end
  def edit
    @user = User.find(session[:user_id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to :action =>'login/show', :notice =>"User Successfully added!"
    else
      render 'login/edit'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      redirect_to @user,:notice => 'User was Successfully Added!'
    else
      render :action => "new"
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "User Successfully added!"
      redirect_to :action =>'show',:controller=>"login"
    else
      render action: "edit"
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to @user,:notice => "User successfully deleted!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sending Mail</title>
  <%= stylesheet_link_tag    "application","users", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="sign">
  <% if current_user %>
      <%= link_to "Account",account_path %>

      <%= link_to image_tag("signout.png",:height=>20),log_out_path %>
  <% else %>
      <%= link_to "Home",home_path %>
      <%= link_to "Login",login_path %>
      <%= link_to "Register",sign_up_path %>
      <%= link_to "aboutus" %>
  <% end %>
</div>


<% flash.each do |name,msg| %>
    <%= msg %>
<% end %>

<%= yield %>






</body>
</html>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/><br/><br/><br/><br/><br/><br/>

<div id="footer" style="background-color: #556b2f;text-align: center;tab-size: 200*50;">
  <p id="copyright">Copyright © ravikishore479@gmail.com</p>
</div>

app/views/login/edit.html.erb
<h2>Edit Personal Details</h2>
<%= form_for(@user) do |f| %>


    <div class="field">
      <%= f.label :firstname %><br />
      <%= f.text_field :firstname %>
    </div>
    <div class="field">
      <%= f.label :lastname%><br />
      <%= f.text_field :lastname %>
    </div>
    <div class="field">
      <%= f.label :sex%><br />
      <%= f.select "sex", options_for_select([ "Male", "Female" ], "Male") %>
    </div>
    <div class="field">
      <%= f.label :mobileno%><br />
      <%= f.text_field :mobileno %>
    </div>
    <div class="field">
      <%= f.label :address%><br />
      <%= f.text_area :address %>
    </div>
    <div class="field">
      <%= f.label :passportno%><br />
      <%= f.text_field :passportno %>
    </div>
    <div class="field">
      <%= f.label :pancardno%><br />
      <%= f.text_field :pancardno %>
    </div>
    <p>
      <% if @user.image.exists? %>
      <%= image_tag(@user.image.url,:height => 100,:width=>100)%><br/>
      <% end %>
      <%= f.label :image, "Attach an Image" %><br />
      <%= f.file_field :image %>
    </p>

    <div class="actions">
      <%= f.submit "submit" %>
    </div>
<% end %>
<%= link_to 'Back', :action=>'show',:controller=>'users',:id => @user.id %>

app/views/login/index.html.erb
vv

app/views/login/new.html.erb
<h1>Sign in</h1>
<%= form_tag login_path do %>
    <p>
      <%= label_tag :email %>
      <%= text_field_tag :email,params[:email] %>
    </p>
    <p>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </p>
    <p class="button">
      <%= submit_tag "signin" %>
    </p>
<% end %>

app/views/login/show.html.erb
<h1> Welcome </h1>

app/views/users/_form.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.erb
<h1>Edit user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :action=>'index' %>

app/views/users/index.html.erb
<h1>Sample SMS-to-Email</h1>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>Form is invalid</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <table class="center">
      <tr>
        <td style="text-align: right;">
          <%= f.label :name %>:</td><td>
          <%= f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td style="text-align: right;">
          <%= f.label :email %>:</td><td>
          <%= f.text_field :email %>
        </td>
      </tr>
      <tr>
        <td style="text-align: right;">
          <%= f.label :password %>:</td><td>
          <%= f.password_field :password %>
        </td>
      </tr>
      <tr>
        <td style="text-align: right;">
          <%= f.label :password_confirmation %>:</td><td>
          <%= f.password_field :password_confirmation %>
        </td>
      </tr>


    </table>
    <table class="center">
      <tr>
        <td>
          <%= f.submit %>
        </td>
      </tr>
    </table>
<% end %>

app/views/users/show.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First_Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', :action=> 'edit',:id => @user.id %>
<%= link_to 'Back', :action=>'index' %>